============================= test session starts ==============================
platform linux -- Python 3.13.1, pytest-8.3.4, pluggy-1.5.0
rootdir: /workspace
collected 21 items
tests/test_a_environment.py .                                            [  4%]
tests/test_a_setup.py ..                                                 [ 14%]
tests/test_data.py ...                                                   [ 28%]
tests/test_decision_tree.py ..FFFF                                       [ 57%]
tests/test_experiment.py .F                                              [ 66%]
tests/test_metrics.py .                                                  [ 71%]
tests/test_numpy.py ......                                               [100%]
=================================== FAILURES ===================================
________________________ test_information_gain_discrete ________________________
>           good.append(round(information_gain(_features, idx, _targets), 3))
tests/test_decision_tree.py:91:
>       if predictions.shape[0] != actual.shape[0]:
E       IndexError: tuple index out of range
src/metrics.py:55: IndexError
_______________________ test_information_gain_continuous _______________________
>       iGX1 = information_gain(_features, 0, _targets)
tests/test_decision_tree.py:110:
>       if predictions.shape[0] != actual.shape[0]:
E       IndexError: tuple index out of range
src/metrics.py:55: IndexError
___________________________ test_decision_tree_run1 ____________________________
>       help_decision_tree_run(order)
tests/test_decision_tree.py:161:
>       if predictions.shape[0] != actual.shape[0]:
E       IndexError: tuple index out of range
src/metrics.py:55: IndexError
___________________________ test_decision_tree_run2 ____________________________
>       help_decision_tree_run(order)
tests/test_decision_tree.py:172:
>       if predictions.shape[0] != actual.shape[0]:
E       IndexError: tuple index out of range
src/metrics.py:55: IndexError
_______________________________ test_comparisons _______________________________
>           acc_a, learner_a = run(data_path_a, method_a, a["fraction"], **kwargs_a)
tests/test_experiment.py:73:
>       if predictions.shape[0] != actual.shape[0]:
E       IndexError: tuple index out of range
src/metrics.py:55: IndexError
=========================== short test summary info ============================
FAILED tests/test_decision_tree.py::test_information_gain_discrete - IndexErr...
FAILED tests/test_decision_tree.py::test_information_gain_continuous - IndexE...
FAILED tests/test_decision_tree.py::test_decision_tree_run1 - IndexError: tup...
FAILED tests/test_decision_tree.py::test_decision_tree_run2 - IndexError: tup...
FAILED tests/test_experiment.py::test_comparisons - IndexError: tuple index o...
========================= 5 failed, 16 passed in 3.79s =========================